### ISSUE TITLE
Buddy At least change the clone link to yours

### ISSUE THREAD

**Issue by chottuthejimmy** [vallabha03/Smart-Traffic-monitoring-system#1]
https://github.com/vallabha03/Smart-Traffic-monitoring-system/blob/37b67a47c34b29d0e8c2e034b1a68f07606ec92d/readme.md?plain=1#L66

Or just give him the credits under **Acknowledgment** section or something

**Comment by vallabha03** [comment]
How to give credits?

**Comment by chottuthejimmy** [comment]
![image](https://github.com/vallabha03/Smart-Traffic-monitoring-system/assets/108192034/45c5fb5f-3d2b-4799-b4b7-0e24175fae14)
Like this

**Comment by vallabha03** [comment]
Ok thank you
